### ISSUE TITLE
AAString + Start & End residues 

### ISSUE THREAD

**Issue by nlgittens** [ococrook/hdxstats#26]
Would it be possible to concatenate AA strings with the Start and End peptide sequences? As I think when analysing data, my brain more easily recollects the important residue numbers rather than the actual sequence, and I think that other people will also be feel similarly. I think carrying forwards residue numbers into the final out@results table will also be help orient users (as below).

![image](https://user-images.githubusercontent.com/90684994/160641624-f643b505-dd58-4b34-b2ec-da670c0c0a07.png)

**Comment by ococrook** [comment]
@broncio123 can you let me know when you've editted the code such that the start and end of the amino acid are in the `QFeatures` object. This can then easily be added to these plots.

**Comment by broncio123** [comment]
> @broncio123 can you let me know when you've editted the code such that the start and end of the amino acid are in the `QFeatures` object. This can then easily be added to these plots.

It's already been done, here
https://github.com/ococrook/hdxstats/blob/5ea787bbc09c18cde359ce5ef5a739b6c6d84af6/R/hdxstat-utils.R#L411 
branch `app_v2`
