### ISSUE TITLE
Add residue numbers to average plots and heatmap plots

### ISSUE THREAD

**Issue by broncio123** [ococrook/hdxstats#28]
For functions located here https://github.com/ococrook/hdxstats/blob/12bd49179a8875746d1221700b9f278e858dee44/R/functionalAnalysis-plots.R

The output plots provided by these functions only display the amino acid sequences along the horizontal axes.
It would be really useful to have residue numbers to quickly locate amino acids too.
Potentially, you can add residue numbers in the upper horizontal axes of the plots, with 90 deg rotated labels to avoid cluttering.

What do you think @ococrook ?

**Comment by ococrook** [comment]
this is now done on v2 branch
