### ISSUE TITLE
Deuterium uptake plotting - linear vs semi-log

### ISSUE THREAD

**Issue by nlgittens** [ococrook/hdxstats#3]
Regarding the peptide uptake plots, it's very difficult to interpret anything visually from the early timepoints because the time dimension is linear in all of the plots. Therefore, the uptake plots look very similar, which may be deceptive since in a semi-log plot, the differences in deuterium uptake might become more apparent. How does the same data look plotted as a semi-log plot (I didn't find an easy way to do this in R with the data in the HdxStatModel class), and is there a rationale for the linear plot (perhaps to start at t = 0, D uptake = 0)?

Perhaps it's easier to take a figure from the paper.

Figure 4a:- "Figure 4 panel d shows the forest plot corresponding to the peptide in Figure panel a. Here, the difference is visually subtle but our functional method identifies a difference between the two samples"

I think Figure 4a it's just very difficult to see what is going on at the early timepoints conclusively whether there is a visual difference or not. 
![image](https://user-images.githubusercontent.com/90684994/141964830-6f075d9d-bb60-4cc7-ad22-b9549d937f9d.png)

**Comment by ococrook** [comment]
I'll see if I can do this easily change the the time axis to log coordinate. I think it should be easy. 

Though there is warning here than the log transform causes problems at 0 and can exessively exagerate changes. I usually prefer the original coordinates unless there is a good reason

**Comment by ococrook** [comment]
@nlgittens There is now a way to do this in the [vignette](https://github.com/ococrook/hdxstats/blob/0f82e2095c34b6a35cc95d66923e734196e1f431/vignette/hdxstats-getting-started.Rmd#L303)

**Comment by ococrook** [comment]
If you're happy could you close the issue?
