### ISSUE TITLE
Add routines for normalisation by time intercept and 'undeuterated' peptide mass into normalisehdx

### ISSUE THREAD

**Issue by broncio123** [ococrook/hdxstats#31]
Function to be modified
https://github.com/ococrook/hdxstats/blob/12bd49179a8875746d1221700b9f278e858dee44/R/hdxstat-utils.R#L33

* Normalise by intercept: To subtract the Deu Uptake value of the first timepoint from subsequent timepoints for a peptide, for single experimental conditions/states.
_Example_
![image](https://user-images.githubusercontent.com/17453074/187926952-9e03fce6-5e33-4947-bc3e-b164a121367d.png)

* Normalise by undeutereated mass of a peptide: Across all experimental conditions/states, for a peptide. 
_Example_
![image](https://user-images.githubusercontent.com/17453074/187927740-7cf8bc3e-25d8-4d47-b2bf-cbf6224a6912.png)

Is this something you already have a modified routine for, @ococrook ?
I guess for the second case, the line from the vignette can be taken.

**Comment by ococrook** [comment]
This is done on the v2 branch?

**Comment by broncio123** [comment]
> This is done on the v2 branch?

Yes, these routines are now part of `normalisehdx`, here
https://github.com/ococrook/hdxstats/blob/77ab9c21681c9bce3c1721e9a9a5f3852dabd80a/R/hdxstat-utils.R#L62-L131

I'll close this issue as the new features have been already implemented.
