### ISSUE TITLE
Is hmpplot functional?

### ISSUE THREAD

**Issue by nlgittens** [ococrook/hdxstats#34]
I wanted to try out this procedure since I was struggling to find any significant results for a dataset yet consistent protection effects for overlapping peptides all point towards there being a protection effect in the bound state. It's present in the vignette but in the R package there is a line "currently in development and not used".

My traceback is: 
```
Error in tailsEstable(x, stableParamObj) : 
NA/NaN/Inf in foreign function call (arg 7)
4.
tailsEstable(x, stableParamObj)
3.
pEstable(w.sum/HMP, setParam(alpha = 1, location = (log(L) + 
O.874), logscale = log(pi/2), pm = 0), lower.tail = FALSE)
2.
harmonicmeanp::p.hmp(butterfly_long[seq.int(i, i + interval), 
"p_value"], L = nrow(butterfly_long))
1.
hmpWindow(params = out, sequences = hdexaminer_table$Sequence, 
region = hdexaminer_table[, c("Start", "End")], interval = 20)
```

**Comment by ococrook** [comment]
Not currently support due to an interpretation issue - how do we combine signficance when we are insure of protection vs deprotection. Will close issue for the moment but we can re-open if this becomes sensible in the future
