### ISSUE TITLE
object undefined in hdxdifference function

### ISSUE THREAD

**Issue by broncio123** [ococrook/hdxstats#35]
`qDF` variable is referenced in line 801 without definition via `object` input argument for `hdxdifference` function
https://github.com/ococrook/hdxstats/blob/12bd49179a8875746d1221700b9f278e858dee44/R/functionalAnalysis-plots.R#L755-L851

**Comment by ococrook** [comment]
This should be object, thanks for spotting!

**Comment by ococrook** [comment]
Is this fixed in the new patch ?

**Comment by broncio123** [comment]
> diff <- assay(qDF)[, cols[2]] - assay(qDF)[, cols[1]]

Yes, fixed already in `app_v2` branch, here
https://github.com/ococrook/hdxstats/blob/77ab9c21681c9bce3c1721e9a9a5f3852dabd80a/R/functionalAnalysis-plots.R#L849 

I'll close this issue as this has been fixed.
