### ISSUE TITLE
processFunctional error

### ISSUE THREAD

**Issue by nlgittens** [ococrook/hdxstats#36]
As per our meeting this morning, these are the error messages and warnings that I have received. No "out" object is created. I am adding in file to our fileshare today.

`> out <- processFunctional(object = hdxstats_tableqDF, params = res)`
Error in if (m == 0) { : missing value where TRUE/FALSE needed
In addition: There were 50 or more warnings (use warnings() to see the first 50)
> 
`> warnings()`
Warning messages:
1: In pf(q = Fstat, df1 = d1, df2 = d2, lower.tail = FALSE) : NaNs produced
2: In pf(q = Fstat, df1 = d1, df2 = d2, lower.tail = FALSE) : NaNs produced
3: In pf(q = Fstat, df1 = d1, df2 = d2, lower.tail = FALSE) : NaNs produced
4: In pf(q = Fstat, df1 = d1, df2 = d2, lower.tail = FALSE) : NaNs produced
5: In pf(q = Fstat, df1 = d1, df2 = d2, lower.tail = FALSE) : NaNs produced
...etc

**Comment by ococrook** [comment]
Hi Nathan

The script you sent works for me - could you double check the error ? Perhaps the ELN .csv isn't correct?

**Comment by nlgittens** [comment]
Hmm... not sure what's going on, I retried it but seemed to work okay and haven't been able to reproduce the error. I'll close this for now and re-open if I an work out the cause.
