### ISSUE TITLE
plotEpitopeMap peptides too long

### ISSUE THREAD

**Issue by nlgittens** [ococrook/hdxstats#37]
This is an issue I only just recognised, but also exists in the HOIP dataset: if you look carefully at the plots from the plotEpitopeMap function, each peptide is 1 residue too long on the N-terminus.

![image](https://user-images.githubusercontent.com/90684994/194872079-a2499346-ed4e-48d7-a448-4ea940982356.png)

![image](https://user-images.githubusercontent.com/90684994/194872449-b7957664-8a13-4b30-bad0-92fcb615f9a8.png)

I noticed this as I was getting a perhaps related error that I couldn't resolve that implies that my fasta file was one residue too long/short, where maximum redundancy = 11:

Error in `$<-.data.frame`(`*tmp*`, "Z", value = c(1L, 1L, 1L, 1L, 1L,  : 
  replacement has 4719 rows, data has 4708

If I artificially reduce the length of the fasta file by 1 aa, the function works. So I also thought that this error occurs when numlines is not a factor of the number of residues (which is an issue when your construct has a prime number of residues!)

**Comment by ococrook** [comment]
Thanks for spotting - for some reason start was offset by -1. Not sure how that got there but it's fixed and will be correct in the next patch
