### ISSUE TITLE
hdxdifference p-value signs

### ISSUE THREAD

**Issue by nlgittens** [ococrook/hdxstats#43]
Putting this as placeholder, as I don't have a dataset I can share with you. Essentially, I have quite a large block of peptides in a protein all of which are protected at all timepoints, yet the difference plot is assigning most as +ve (deprotecting), along with some -ve residues. I don't think that this is just because of overlapping peptides. p-values are identical as to when computeAverageMap is used, I just can't rationalise the sign at all; it would be useful to parse through this

**Comment by ococrook** [comment]
The sign comes from the raw uptake data what are you're inputs to the function?
