### ISSUE TITLE
Heat map cosmetics

### ISSUE THREAD

**Issue by nlgittens** [ococrook/hdxstats#5]
Minor point:- Experimentalists would want to see the start-to-end residue numbers in the peptides for the heat map (along the x-axis): makes it easy to pick out regions-of-interest in the protein, and also see which peptides are overlapping. Likely these can easily be concatenated in.

![image](https://user-images.githubusercontent.com/90684994/142407312-38c7a6b5-87b7-47a0-ab59-5f61a8ca11c9.png)

**Comment by ococrook** [comment]
Thanks @nlgittens! This option has now been added to the [vignette](https://github.com/ococrook/hdxstats/blob/a77ea6d3b731547647a184b3aaf9c6cf7515c046/vignette/hdxstats-getting-started.Rmd#L161).

If you are happy could you close the issue?
