### ISSUE TITLE
Residue plot colours

### ISSUE THREAD

**Issue by ococrook** [ococrook/hdxstats#7]
Residue plots with with colour gradient for deprotection/protection with pvalues

**Comment by ococrook** [comment]
red (deprection), white, blue (protected)

**Comment by ococrook** [comment]
@nlgittens how does the following look to you? 
![image](https://user-images.githubusercontent.com/23522532/143027213-a19c9a1d-7f9b-4e06-91cc-a0f7f23e3268.png)

**Comment by ococrook** [comment]
These have now been added to the package, if you're happy could you close the issue?

**Comment by nlgittens** [comment]
Works in principle, but having some issues with getting the data into the graph object; at the moment it comes in all grey as if there is no data. Think this is an R/RStudio issue rather hdxstats; I'm still having some issues upstream that I need to try to resolve, so sorry I haven't quite got to resolving this yet.

**Comment by ococrook** [comment]
have you updated the package, I had this problem and it worked after I updated
